---
title: EVENTOS DM2
author: "Jordi Real"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

# LECTURA DE DADES --------------------------

# 1. Setup ------

rm(list=ls())

# 2. Carrega de funcions ----------
link_source<-paste0("https://github.com/jrealgatius/Stat_codis/blob/master/funcions_propies.R","?raw=T")
devtools::source_url(link_source)

# 3. Lectura de dades ------------ 
library(here)
library(compareGroups)

```


# 1. Leer ficheros de eventos
# 2. Formatear etc...
# 3. En BD_CIPS Fusionar eventos agrupados segun cataleg


```{r lectura}


input_dades<-here::here("dades","BD_CIPS_N951.sav")

BD_CIPS<-read.spss(input_dades,to.data.frame = T) %>% as_tibble()

```

# 4. Lectura de cataleg i dades d'events CV  -------------------

```{r}
dt_cataleg<-"dades" %>% here::here("catalogo_codigos.xls") %>% read_excel(sheet = "ECV_EXITUS") %>% netejar.noms.variables()
EVENTOS_CV<-"dades" %>% here::here("EVENTOS_CARDIOVASCULARES.xls") %>% read_excel() %>% netejar.noms.variables()
EVENTOS_CV_EXIT<-"dades" %>% here::here("EVENTOS_CARDIOVASCULARES_EXITUS.xls") %>% read_excel() %>% netejar.noms.variables()
EVENTOS_EXIT_TOTAL<-"dades" %>% here::here("EXITUS_todos.xls") %>% read_excel() %>% netejar.noms.variables()
EVENTOS_CV_PROC<-"dades" %>% here::here("EVENTOS_CARDIOVASCULARES_PROCEDIM.xls") %>% read_excel() %>% netejar.noms.variables()

```


# 5. Fusió d'events CV ----------------

```{r fusio}

EVENTOS_TOTAL<-EVENTOS_CV %>% rbind(EVENTOS_CV_EXIT) %>% rbind(EVENTOS_EXIT_TOTAL)

# Reformat procediments_CV
EVENTOS_CV_PROC<-EVENTOS_CV_PROC %>% rename(Diagnstic_codi=Procediment_codi,Diagnstic_desc=Procediment_desc)

# Fusió total
HISTORIC_EVENTOS_TOTAL<-EVENTOS_TOTAL %>% rbind(EVENTOS_CV_PROC) %>% rename(idp=CIP_14d) %>% select(idp,cod=Diagnstic_codi,Data_ingres)


```

# 5. Formateig (CIPS A 13 DIGITS)

# Ids CIPS --> a 13 digits 

```{r formateig}

HISTORIC_EVENTOS_TOTAL<-HISTORIC_EVENTOS_TOTAL %>% mutate(idp=str_sub(idp,1,13)) %>% 
  select(idp,cod,dat=Data_ingres) %>% 
  mutate(dat=data_convert_UTC(dat)) 
# 
IDS_CIPS<-BD_CIPS %>% select(CIP, Inclusion) %>% mutate(dtindex=dataSPSS_to_Rdata(Inclusion),idp=as.character(CIP)) %>% select(idp,dtindex) %>%
  mutate(idp=str_sub(idp,1,13))

#
dt_cataleg<-dt_cataleg %>% select(cod=Diagnstic_codi,Agrupador1,Agrupador2,Agrupador3,MCV)

```


# 6. Agregar problemes de salut ----------------------

```{r agregar_problemes}
dt_agregada<-agregar_problemes(dt=HISTORIC_EVENTOS_TOTAL, bd.dindex = IDS_CIPS,dt.agregadors = dt_cataleg,finestra.dies = c(0,+Inf),prefix = "DG.",camp_agregador = "Agrupador1")
dt_agregada2<-agregar_problemes(dt=HISTORIC_EVENTOS_TOTAL, bd.dindex = IDS_CIPS,dt.agregadors = dt_cataleg,finestra.dies = c(0,+Inf),prefix = "DG.",camp_agregador = "Agrupador2")
dt_agregada3<-agregar_problemes(dt=HISTORIC_EVENTOS_TOTAL, bd.dindex = IDS_CIPS,dt.agregadors = dt_cataleg,finestra.dies = c(0,+Inf),prefix = "DG.",camp_agregador = "Agrupador3")
dt_agregada4<-agregar_problemes(dt=HISTORIC_EVENTOS_TOTAL, bd.dindex = IDS_CIPS,dt.agregadors = dt_cataleg,finestra.dies = c(0,+Inf),prefix = "DG.",camp_agregador = "MCV")

dt_agregada<-dt_agregada %>% full_join(dt_agregada2) %>% full_join(dt_agregada3) %>% full_join(dt_agregada4)

rm(list=c("dt_agregada2","dt_agregada3","dt_agregada4")) 

```


# 7. Agregar per font (Base de dades) --------------------

```{r agregar_font}

# Mortalitat event CV ----------------
historic_eventos_MCV<-EVENTOS_CV_EXIT %>% mutate (idp=str_sub(CIP_14d,1,13),data_MCV=data_convert_UTC(Data_ingres)) %>% 
  select(idp,cod_MCV=Diagnstic_codi,data_MCV)
# Join 
idp_MCV<-IDS_CIPS %>% left_join(historic_eventos_MCV,by="idp")

# Mortalitat global ----------------
historic_eventos_exitus<-EVENTOS_EXIT_TOTAL %>% mutate (idp=str_sub(CIP_14d,1,13),data_exitus=data_convert_UTC(Data_ingres)) %>% 
  select(idp,cod_exitus=Diagnstic_codi,data_exitus)
# Join 
idp_MCV<-idp_MCV %>% left_join(historic_eventos_exitus,by="idp")

# Eventos CV ----------------
historic_CV<-EVENTOS_CV %>% rbind(EVENTOS_CV_EXIT) %>% rbind(EVENTOS_CV_PROC) %>% mutate (idp=str_sub(CIP_14d,1,13),data1_CV=data_convert_UTC(Data_ingres)) %>%
  select(idp,cod_CV1=Diagnstic_codi,data1_CV)
# Join 

idp_CV<-IDS_CIPS %>% left_join(historic_CV,by="idp") %>% group_by(idp) %>% arrange(dtindex) %>% slice(1) %>% ungroup() 

idp_tots<-idp_MCV %>% left_join(idp_CV,by="idp")

rm(list=c("historic_eventos_MCV","historic_CV","historic_eventos_exitus","idp_MCV","idp_CV"))


```

# 8 Fusionar tot -------------------

```{r fusionar_tot}
#
#
dades_dt<-BD_CIPS %>% 
  mutate(idp=str_sub(CIP,1,13)) %>% 
  left_join(IDS_CIPS,by="idp") %>% 
  left_join(select(dt_agregada,-dtindex),by="idp") %>% 
  left_join(select(idp_tots,-c(dtindex.x,dtindex.y)),by="idp") 


dades_dt<- dades_dt %>% mutate(data_sortida=20171231)


```


# 9 Parametres  --------------

```{r parametres}

conductor_variables<-here::here("variables_eventos.xls")

llista_events<-extreure.variables("events",taulavariables = conductor_variables)

```


# 10 Calculs ----------------

Genera dades_surv

```{r calculs}
dades_surv<-map(llista_events,~generar_Surv(dt=dades_dt,event=.,dtindex = "dtindex",dtsortida="data_sortida")) %>% 
  as.data.frame()

# Fusiona amb dades  
dades_dt<-dades_dt %>% cbind(dades_surv)


# Generara events
dades_dt<-dades_dt %>% mutate_at(vars(llista_events), 
                                 funs(ifelse(is.na(.),0,1))) 

# Factoritzacio
dades_dt<-factoritzar.NO.YES(dades_dt,"events",taulavariables=conductor_variables)



```

# Descriptiva 
```{r descriptiva}

formula<-formula_compare("events","GRUPO",taulavariables = conductor_variables)
taula<-descrTable(formula,data=dades_dt, show.p.overall = F)


export2md(taula)

```




